# Generated by Django 5.2.5 on 2025-08-09 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "resolution_max",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "resolution_min",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fps_max", models.IntegerField(blank=True, null=True)),
                ("fps_min", models.IntegerField(blank=True, null=True)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                ("camera_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "camera_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("camera_key", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "camera_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="provision.camerainfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
