# Generated by Django 5.2.5 on 2025-09-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provision", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=50)),
                ("position", models.JSONField(blank=True, null=True)),
                ("acknowledged", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("snapshot_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Camera",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
