# Generated by Django 5.2.5 on 2025-09-20 13:20

import provision.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provision", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigIntegerField(
                default=provision.models.users.generate_snowflake_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
