# Generated by Django 5.2.8 on 2025-11-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_conversation_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
